### ISSUE TITLE
VRDB feedback

### ISSUE THREAD

**Issue by MattFiler** [DBolical/Home#51]
So I just got to try VRDB. It is amazing, such an improvement over the style of ModDB and other sites, feels familiar in the styles and layout but it's so much simpler and awesome being responsive.

I feel like the searching could be handled a bit better when the user doesn't enter a query. Presenting a squashed up page telling you to enter something could be solved easily using JavaScript or PHP and doing a quick form validation before it's submitted. You could then highlight the search box red if the user doesn't enter anything instead of redirecting them to that page.

I also noticed that some profile pictures seem to be missing on people's accounts just giving a blank  default "no image" thing that browsers do. Is this a site error or a user error? If it's that the user's image is blank then it could obviously be handled a bit better, otherwise you might need to check some profile picture URLs, etc and make sure they haven't been deleted!

Where are profile headers used in the new version? I thought they'd be set as the background of the top of the profile but I can't seem to see them being used anywhere. 

Those are my only complaints/reports, the new site is looking superb. So cool. Really hope ModDB gets an update to that design at some point!

**Comment by intenscia** [comment]
Pleased that you like it, appreciate the feedback. What do you mean by "squashed up page" what is squashed when you search? And yes we plan on making the search ajax and instant, so that is coming.

Profile pictures should appear if you refresh the page. Our sites cache is currently being built so it might take a few days.

We are moving away from profile headers and will be giving users other ways to customize the design and presentation of their profile.

**Comment by MattFiler** [comment]
Thanks for the reply.

[This is what I mean by "squashed up".](http://i.imgur.com/VrOUxkZ.png)

Nice to see you're already working on or know about the things I've reported! It looks like you guys are doing a superb job.

Can't wait to see the finished product!

**Comment by intenscia** [comment]
Search should be fixed - really appreciate the postive feedback :+1:
